---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.0
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.8
  run_list: ["recipe[apt]"]
- name: fedora-19
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20
- name: fedora-21
- name: opensuse-13.1
  driver_config:
    box: opscode-opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box
# FreeBSD platform requires to run kitchen verify twice by hand
# - name: freebsd-9.2
#   run_list: ["recipe[freebsd::portsnap]"]
#   driver_config:
#     box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-9.2_chef-provisionerless.box
# - name: freebsd-10.1
#   run_list: ["recipe[freebsd::portsnap]"]
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: ubuntu-16.04
  run_list: ["recipe[apt]"]
- name: ubuntu-18.04
  run_list: ["recipe[apt]"]

suites:
<% %w(0.6.0 0.5.0 0.3.0).unshift(nil).each do |gemver| %>
<%   if gemver.nil? ||
        Gem::Requirement.new('> 0.3').satisfied_by?(Gem::Version.new(gemver)) %>
     # chef-encrypted-attributes 0.3.0 only works with Chef 11 due to depends
- name: gem<%= gemver || 'latest' %>
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
    <% unless gemver.nil? %>
      version: <%= gemver %>
    <% end %>
<%   end %>
- name: gem<%= gemver || 'latest' %>-chef11
  provisioner:
    require_chef_omnibus: 11.16.4
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
    <% unless gemver.nil? %>
      version: <%= gemver %>
    <% end %>
- name: gem<%= gemver || 'latest' %>-chef11old
  excludes:
  - opensuse-13.1
  provisioner:
    require_chef_omnibus: 11.12.8
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
    <% unless gemver.nil? %>
      version: <%= gemver %>
    <% end %>
<% end %>
- name: key
  run_list:
    - recipe[encrypted_attributes_test::expose_key]
